:wink: add ninja build excutable
tipi-build/distro pull request #38
Opened 2023-08-04 14:01 UTC by Lambourl

the purpose of this Pr is to add ninja to our tools

2023-08-09 19:26 UTC, daminetreg approved these changes
Simple, effective.

2023-09-05 07:11 UTC, daminetreg commented on distro.json
> +            "root": "environments-99b29c25efce9cc6445a857262e6536659aa5777"
This requires changes there are obvious issue in the environments fiels.

2023-09-05 07:12 UTC, daminetreg requested changes

2023-09-05 07:12 UTC, daminetreg commented on distro.json
> +            "root": "environments-99b29c25efce9cc6445a857262e6536659aa5777"
See my review on https://github.com/tipi-build/environments/pull/21

2023-09-06 12:57 UTC, pysco68 approved these changes
LGTM

2023-09-06 12:57 UTC, merged